// This file is part of the extension to AliceVision project.
// Copyright (c) 2026 AliceVision contributors.
// This Source Code Form is subject to the terms of the Mozilla Public License,
// v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

/**
 * This file generates a .metal file containing a pre-defined set of gaussian
 * values.
 */

#include "../Config.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

const char* OUT_FILE_HEADER =
    "// This file is part of the extension to AliceVision project.\n"
    "// Copyright (c) 2026 AliceVision contributors.\n"
    "// This Source Code Form is subject to the terms of the Mozilla Public License,\n"
    "// v. 2.0. If a copy of the MPL was not distributed with this file,\n"
    "// You can obtain one at https://mozilla.org/MPL/2.0/.\n"
    "\n"
    "/* This file is auto-generated by generate_gauss_array. Do not edit! */\n"
    "\n"
    "#include <aliceVision/depthMap_mtl/Config.h>\n"
    "#include <aliceVision/depthMap_mtl/Namespace.hpp>\n"
    "\n"
    "ALICEVISION_DEPTHMAP_MTL_NS_START\n"
    "\n";

const char* OUT_FILE_TRAILER =
    "\nALICEVISION_DEPTHMAP_MTL_NS_END\n";

int main(int argc, char** argv) {

    if (argc < 2)
    {
        fprintf(stderr, "Expected a single argument for the absolute output file path!\n");
        exit(EXIT_FAILURE);
    }

    int sumSizes = 0;

    int h_gaussianArrayOffset[ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_SCALES];
    float h_gaussianArray[ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_MEM_SIZE];

    for(int scale = 0; scale < ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_SCALES; ++scale)
    {
        h_gaussianArrayOffset[scale] = sumSizes;
        const int radius = scale + 1;
        const int size = 2 * radius + 1;
        sumSizes += size;
    }

    if (sumSizes > ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_MEM_SIZE) {
        fprintf(stderr, "Gaussian array exceeds max size!\n");
        exit(EXIT_FAILURE);
    }

    for(int scale = 0; scale < ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_SCALES; ++scale)
    {
        const int radius = scale + 1;
        const float delta  = 1.0f;
        const int size   = 2 * radius + 1;

        for(int idx = 0; idx < size; idx++)
        {
            int x = idx - radius;
            h_gaussianArray[h_gaussianArrayOffset[scale]+idx] = expf(-(x * x) / (2 * delta * delta));
        }
    }

    /* Open File */
    FILE* outFile = fopen(argv[1], "w+");
    if (outFile == NULL)
    {
        fprintf(stderr, "The specified out file '%s' could not be opened for writing!\n", argv[1]);
        exit(EXIT_FAILURE);
    }

    /* Print Header */
    fprintf(outFile, "%s", OUT_FILE_HEADER);

    /* Print Offset Array */
    fprintf(outFile, "__attribute__((used))\nextern constant constexpr const int\nd_gaussianArrayOffset[ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_SCALES] =\n{");

    int upToSixteen = 0;
    for (int i = 0; i < ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_SCALES; i++)
    {
        if (upToSixteen == 16)
            upToSixteen = 0;
        if (upToSixteen == 0)
            // Indent width is 4 per .clang-format
            fprintf(outFile, "\n   ");

        fprintf(outFile, " %i,", h_gaussianArrayOffset[i]);

        upToSixteen++;
    }

    fprintf(outFile, "\n};\n\n");

    /* Print Gauss Array */
    fprintf(outFile, "__attribute__((used))\nextern constant constexpr const float\nd_gaussianArray[ALICEVISION_DEPTHMAP_MAX_CONSTANT_GAUSS_MEM_SIZE] =\n{");

    int upToFour = 0;
    for (int i = 0; i < sumSizes; i++)
    {
        if (upToFour == 4)
            upToFour = 0;
        if (upToFour == 0)
            // Indent width is 4 per .clang-format
                fprintf(outFile, "\n   ");

        fprintf(outFile, " %f,", h_gaussianArray[i]);

        upToFour++;
    }

    fprintf(outFile, "\n};\n");

    /* Print Trailer */
    fprintf(outFile, "%s", OUT_FILE_TRAILER);

    /* Flush buffer */
    fflush(outFile);

    /* Close file */
    fclose(outFile);

    return EXIT_SUCCESS;
}
