#
# Build_OpenCV.cmake
#
# Builds an embedded version of OpenCV

include(AV_ColoredMessage)

function(build_OpenCV)

  set(AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS)
  if(AV_USE_IMAGE_CODECS MATCHES "OpenJPEG")
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_OPENJPEG=ON)
  else()
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_OPENJPEG=OFF)
  endif()
  if(AV_USE_IMAGE_CODECS MATCHES "JPEG-XL")
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_JPEGXL=ON)
  else()
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_JPEGXL=OFF)
  endif()
  if(AV_USE_IMAGE_CODECS MATCHES "WebP")
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_WEBP=ON)
  else()
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_WEBP=OFF)
  endif()
  if(AV_USE_IMAGE_CODECS MATCHES "PNG")
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_PNG=ON)
  else()
    list(APPEND AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS -DWITH_PNG=OFF)
  endif()

  # FIXME: Remove when we don't need to pass manual linker flags anymore
  if(${CMAKE_GENERATOR} STREQUAL "Xcode")
    set(AV_DEP_OpenCV_XL_XCODE_FIX -G "Unix Makefiles")
  endif()

  set(AV_DEP_OpenCV_VERSION           "4.13.0")
  set(AV_DEP_OpenCV_URL               "https://github.com/opencv/opencv/archive/refs/tags/${AV_DEP_OpenCV_VERSION}.tar.gz")
  set(AV_DEP_OpenCV_HASH              "SHA256=1d40ca017ea51c533cf9fd5cbde5b5fe7ae248291ddf2af99d4c17cf8e13017d")
  set(AV_DEP_OpenCVContrib_URL        "https://github.com/opencv/opencv_contrib/archive/refs/tags/${AV_DEP_OpenCV_VERSION}.tar.gz")
  set(AV_DEP_OpenCVContrib_HASH       "SHA256=1e0077a4fd2960a7d2f4c9e49d6ba7bb891cac2d1be36d7e8e47aa97a9d1039b")
  set(AV_DEP_OpenCV_EXTRA_CMAKE_FLAGS
    -DOPENCV_FORCE_3RDPARTY_BUILD=OFF
    -DBUILD_ZLIB=OFF
    -DBUILD_TIFF=OFF
    -DBUILD_OPENJPEG=OFF
    -DBUILD_JASPER=OFF
    -DBUILD_JPEG=OFF
    -DBUILD_PNG=OFF
    -DBUILD_OPENEXR=OFF
    -DBUILD_WEBP=OFF
    -DBUILD_TBB=OFF
    -DBUILD_IPP_IW=OFF
    -DBUILD_ITT=OFF
    -DWITH_1394=OFF
    -DWITH_AVFOUNDATION=ON
    -DWITH_AVIF=OFF
    -DWITH_CAP_IOS=OFF
    -DWITH_CAROTENE=OFF
    -DWITH_KLEIDICV=OFF
    -DWITH_NDSRVP=OFF
    -DWITH_HAL_RVV=OFF
    -DWITH_FASTCV=OFF
    -DWITH_CPUFEATURES=OFF
    -DWITH_VTK=OFF
    -DWITH_CUDA=${AV_USE_CUDA}
    -DWITH_CUFFT=OFF
    -DWITH_CUBLAS=OFF
    -DWITH_CUDNN=OFF
    -DWITH_NVCUVID=OFF
    -DWITH_NVCUVENC=OFF
    -DWITH_EIGEN=ON   # We always build Eigen
    -DWITH_FFMPEG=OFF   # FIXME: Update
    -DWITH_GSTREAMER=OFF
    -DWITH_GTK=OFF
    -DWITH_GTK_2_X=OFF
    -DWITH_FRAMEBUFFER=OFF
    -DWITH_FRAMEBUFFER_XVFB=OFF
    -DWITH_WAYLAND=OFF
    -DWITH_IPP=OFF
    -DWITH_HALIDE=OFF
    -DWITH_VULKAN=OFF
    -DWITH_OPENVINO=OFF
    -DWITH_WEBNN=OFF
    -DWITH_JASPER=OFF
    -DWITH_OPENGL=OFF
    -DWITH_OPENVX=OFF
    -DWITH_OPENNI=OFF
    -DWITH_OPENNI2=OFF
    -DWITH_SPNG=OFF
    -DWITH_GDCM=OFF
    -DWITH_PVAPI=OFF
    -DWITH_ARAVIS=OFF
    -DWITH_QT=OFF
    -DWITH_WIN32UI=OFF
    -DWITH_TBB=ON
    -DWITH_HPX=OFF
    -DWITH_OPENMP=${AV_USE_OPENMP}
    -DWITH_PTHREADS_PF=OFF
    -DWITH_V4L=OFF
    -DWITH_DSHOW=OFF
    -DWITH_MSMF=OFF
    -DWITH_MSMF_DXVA=OFF
    -DWITH_XIMEA=OFF
    -DWITH_UEYE=OFF
    -DWITH_XINE=OFF
    -DWITH_CLP=ON
    -DWITH_OPENCL=OFF
    -DWITH_OPENCL_SVM=OFF
    -DWITH_OPENCLAMDFFT=OFF
    -DWITH_OPENCLAMDBLAS=OFF
    -DWITH_DIRECTX=OFF
    -DWITH_DIRECTML=OFF
    -DWITH_OPENCL_D3D11_NV=OFF
    -DWITH_LIBREALSENSE=OFF
    -DWITH_VA=OFF
    -DWITH_VA_INTEL=OFF
    -DWITH_MFX=OFF
    -DWITH_GDAL=OFF
    -DWITH_GPHOTO2=OFF
    -DWITH_LAPACK=ON
    -DWITH_ITT=OFF
    -DWITH_PROTOBUF=OFF
    -DWITH_IMGCODEC_GIF=OFF
    -DWITH_IMGCODEC_HDR=OFF
    -DWITH_IMGCODEC_SUNRASTER=OFF
    -DWITH_IMGCODEC_PXM=OFF
    -DWITH_IMGCODEC_PFM=OFF
    -DWITH_QUIRC=OFF
    -DWITH_ANDROID_MEDIANDK=OFF
    -DWITH_ANDROID_NATIVE_CAMERA=OFF
    -DWITH_ONNX=OFF # We do not build ONNX ourselves
    -DWITH_TIMVX=OFF
    -DOBSENSOR_USE_ORBBEC_SDK=OFF
    -DWITH_OBSENSOR=OFF
    -DWITH_CANN=OFF
    -DWITH_FLATBUFFERS=OFF
    -DWITH_ZLIB_NG=OFF
    -DBUILD_opencv_apps=OFF
    -DBUILD_opencv_js=OFF
    -DBUILD_ANDROID_PROJECTS=OFF
    -DBUILD_ANDROID_EXAMPLES=OFF
    -DBUILD_DOCS=OFF
    -DBUILD_EXAMPLES=OFF
    -DBUILD_PACKAGE=OFF
    -DBUILD_PERF_TESTS=OFF
    -DBUILD_TESTS=OFF
    -DBUILD_WITH_DEBUG_INFO=OFF
    -DBUILD_WITH_STATIC_CRT=OFF
    -DBUILD_WITH_DYNAMIC_IPP=OFF
    -DBUILD_FAT_JAVA_LIB=OFF
    -DBUILD_ANDROID_SERVICE=OFF
    -DBUILD_CUDA_STUBS=OFF
    -DBUILD_JAVA=OFF
    -DBUILD_OBJC=OFF
    -DBUILD_KOTLIN_EXTENSIONS=OFF
    -DINSTALL_CREATE_DISTRIB=OFF
    -DINSTALL_BIN_EXAMPLES=OFF
    -DINSTALL_C_EXAMPLES=OFF
    -DINSTALL_PYTHON_EXAMPLES=OFF
    -DINSTALL_ANDROID_EXAMPLES=OFF
    -DINSTALL_TO_MANGLED_PATHS=OFF
    -DINSTALL_TESTS=OFF
    -DENABLE_CCACHE=OFF
    -DENABLE_PRECOMPILED_HEADERS=OFF
    -DENABLE_DELAYLOAD=OFF
    -DENABLE_SOLUTION_FOLDERS=OFF
    -DENABLE_PROFILING=OFF
    -DENABLE_COVERAGE=OFF
    -DOPENCV_ENABLE_MEMORY_SANITIZER=OFF
    -DENABLE_OMIT_FRAME_POINTER=ON
    -DENABLE_POWERPC=OFF
    -DENABLE_FAST_MATH=OFF
    -DENABLE_NOISY_WARNINGS=OFF
    -DOPENCV_WARNINGS_ARE_ERRORS=OFF
    -DANDROID_EXAMPLES_WITH_LIBS=OFF
    -DENABLE_IMPL_COLLECTION=OFF
    -DENABLE_INSTRUMENTATION=OFF
    -DENABLE_GNU_STL_DEBUG=OFF
    -DENABLE_BUILD_HARDENING=OFF
    -DENABLE_LTO=${AV_BUILD_WITH_LTO}
    -DENABLE_THIN_LTO=ON
    -DGENERATE_ABI_DESCRIPTOR=OFF
    -DOPENCV_GENERATE_PKGCONFIG=OFF
    -DCV_ENABLE_INTRINSICS=ON
    -DCV_DISABLE_OPTIMIZATION=OFF
    -DCV_TRACE=OFF
    -DOPENCV_GENERATE_SETUPVARS=OFF
    -DENABLE_CONFIG_VERIFICATION=OFF
    -DOPENCV_ENABLE_MEMALIGN=ON
    -DOPENCV_DISABLE_FILESYSTEM_SUPPORT=OFF
    -DOPENCV_DISABLE_THREAD_SUPPORT=OFF
    -DOPENCV_DISABLE_ENV_SUPPORT=OFF
    -DOPENCV_SEMIHOSTING=OFF
    -DENABLE_CUDA_FIRST_CLASS_LANGUAGE=ON
    -DENABLE_PYLINT=OFF
    -DENABLE_FLAKE8=OFF
    -DWITH_JPEG=ON
    -DWITH_OPENEXR=ON
    -DWITH_TIFF=ON
    -DBUILD_opencv_python2=OFF
    -DBUILD_opencv_python3=OFF
    -DBUILD_LIST=core,improc,photo,objdetect,video,imgcodecs,videoio,features2d,xfeatures2d,version,mcc,optflow
    ${AV_DEP_OpenCV_ADDITIONAL_CODEC_ARGS}
    ${AV_DEP_OpenCV_XL_XCODE_FIX}
  )

  # Return early if the dependency should not be built
  if(AV_DEP_OpenCV_BUILD_NO_BUILD)
    av_colored_message(PLAIN W "Skipping build of OpenCV...")
    return()
  endif()

  # OpenCV, why do you use weird variable names which cause linker issues?
  # On macOS, we just hard-link libPNG, zlib and OpenMP
  if(APPLE)
    # Must add the install prefix as linker search path (for OpenMP and PNG)
    set(AV_DEP_OpenCV_ADD_LDFLAGS -DCMAKE_SHARED_LINKER_FLAGS=-Wl,-L${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR})
    string(APPEND AV_DEP_OpenCV_ADD_LDFLAGS ",-lz")  # For zlib
    if(AV_USE_OPENMP)
      string(APPEND AV_DEP_OpenCV_ADD_LDFLAGS ",-lomp")  # For OpenMP
    endif()
    if(AV_USE_IMAGE_CODECS MATCHES "PNG")
      string(APPEND AV_DEP_OpenCV_ADD_LDFLAGS ",-lpng")  # For libPNG
    endif()
    list(APPEND AV_DEP_OpenCV_EXTRA_CMAKE_FLAGS ${AV_DEP_OpenCV_ADD_LDFLAGS})
  endif()

  # Get the contrib modules if required
  if(AV_USE_OPENCV_CONTRIB)
    av_make_dependency_available(OpenCVContrib URL ${AV_DEP_OpenCVContrib_URL} URL_HASH "${AV_DEP_OpenCVContrib_HASH}" NO_COUNT)
    list(APPEND AV_DEP_OpenCV_EXTRA_CMAKE_FLAGS
      -DOPENCV_EXTRA_MODULES_PATH=${CMAKE_BINARY_DIR}/ThirdParty/${AV_TARGET_TRIPLE}/OpenCVContrib/modules
    )
  endif()

  # Make the target available
  av_make_dependency_available(OpenCV URL ${AV_DEP_OpenCV_URL} URL_HASH "${AV_DEP_OpenCV_HASH}")

  # Build the dependency
  av_build_cmake_dependency(OpenCV
    EXTRA_CMAKE_ARGS ${AV_DEP_OpenCV_EXTRA_CMAKE_FLAGS}
  )

endfunction()

# Invoke the function automatically
build_OpenCV()
