#
# Build_USD.cmake
#
# Builds an embedded version of USD

include(AV_ColoredMessage)

function(build_USD)

  set(AV_DEP_USD_BUILD_STATIC OFF)
  if(NOT BUILD_SHARED_LIBS)
    set(AV_DEP_USD_BUILD_STATIC ON)
  endif()

  set(AV_DEP_USD_VERSION           "26.05")
  set(AV_DEP_USD_URL               "https://github.com/PixarAnimationStudios/OpenUSD/archive/refs/tags/v${AV_DEP_USD_VERSION}.tar.gz")
  set(AV_DEP_USD_HASH              "SHA256=bf514f62ac9508d3c5b121dc1107f3b29bf3c954473b9b0bf8324b7cf04c64c1")
  set(AV_DEP_USD_EXTRA_CMAKE_FLAGS
    -DPXR_STRICT_BUILD_MODE=OFF
    -DPXR_VALIDATE_GENERATED_CODE=OFF
    -DPXR_HEADLESS_TEST_MODE=OFF
    -DPXR_BUILD_TESTS=OFF
    -DPXR_BUILD_EXAMPLES=OFF
    -DPXR_BUILD_TUTORIALS=OFF
    -DPXR_BUILD_USD_TOOLS=OFF
    -DPXR_BUILD_IMAGING=ON
    -DPXR_BUILD_EMBREE_PLUGIN=OFF
    -DPXR_BUILD_OPENIMAGEIO_PLUGIN=ON
    -DPXR_BUILD_IMAGEIO_PLUGIN=ON
    -DPXR_BUILD_OPENCOLORIO_PLUGIN=ON
    -DPXR_BUILD_USD_IMAGING=ON
    -DPXR_BUILD_USD_VALIDATION=OFF
    -DPXR_BUILD_EXEC=OFF
    -DPXR_BUILD_USDVIEW=OFF
    -DPXR_BUILD_ALEMBIC_PLUGIN=${AV_USE_ALEMBIC}
    -DPXR_BUILD_DRACO_PLUGIN=OFF
    -DPXR_BUILD_PRMAN_PLUGIN=OFF
    -DPXR_ENABLE_MATERIALX_SUPPORT=OFF
    -DPXR_BUILD_DOCUMENTATION=OFF
    -DPXR_BUILD_PYTHON_DOCUMENTATION=OFF
    -DPXR_BUILD_HTML_DOCUMENTATION=OFF
    -DPXR_ENABLE_PYTHON_SUPPORT=OFF
    -DPXR_USE_DEBUG_PYTHON=OFF
    -DPXR_ENABLE_HDF5_SUPPORT=OFF
    -DPXR_ENABLE_OSL_SUPPORT=OFF
    -DPXR_ENABLE_PTEX_SUPPORT=OFF
    -DPXR_ENABLE_OPENVDB_SUPPORT=OFF
    -DPXR_BUILD_MAYAPY_TESTS=OFF
    -DPXR_BUILD_ANIMX_TESTS=OFF
    -DPXR_ENABLE_NAMESPACES=ON
    -DPXR_PREFER_SAFETY_OVER_SPEED=ON
    -DPXR_ENABLE_METAL_SUPPORT=OFF
    -DPXR_ENABLE_VULKAN_SUPPOR=OFF
    -DPXR_ENABLE_GL_SUPPORT=OFF
    -DPXR_BUILD_MONOLITHIC=ON
    -DALEMBIC_DIR=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/cmake/Alembic
  )

  # Return early if the dependency should not be built
  if(AV_DEP_USD_BUILD_NO_BUILD)
    av_colored_message(PLAIN W "Skipping build of USD...")
    return()
  endif()

  # Make the target available
  av_make_dependency_available(USD URL ${AV_DEP_USD_URL} URL_HASH "${AV_DEP_USD_HASH}")

  # Build the dependency
  av_build_cmake_dependency(USD
    EXTRA_CMAKE_ARGS ${AV_DEP_USD_EXTRA_CMAKE_FLAGS}
  )

endfunction()

# Invoke the function automatically
build_USD()
