#
# AV_DetermineTargetTriple.cmake
#
# This file sets AV_TARGET_TRIPLE which holds the LLVM-like target-triple

if(WIN32)
  if(AV_COMPILER_IS_MSVC)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(AMD64|IA64)")
      set(AV_TARGET_TRIPLE "x86_64-pc-windows-msvc" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ARM64")
      set(AV_TARGET_TRIPLE "aarch64-pc-windows-msvc" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "X86")
      set(AV_TARGET_TRIPLE "i686-pc-windows-msvc" CACHE INTERNAL "The LLVM-like target triple")
    else()
      message(FATAL_ERROR "Unknown Windows architecture: ${CMAKE_SYSTEM_PROCESSOR}!")
    endif()
  elseif(AV_COMPILER_IS_LLVM)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(AMD64|IA64)")
      set(AV_TARGET_TRIPLE "x86_64-pc-windows-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ARM64")
      set(AV_TARGET_TRIPLE "aarch64-pc-windows-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "X86")
      set(AV_TARGET_TRIPLE "i686-pc-windows-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    else()
      message(FATAL_ERROR "Unknown Windows architecture: ${CMAKE_SYSTEM_PROCESSOR}!")
    endif()
  elseif(AV_COMPILER_IS_GNU)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(AMD64|IA64)")
      set(AV_TARGET_TRIPLE "x86_64-pc-windows-gnu" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ARM64")
      set(AV_TARGET_TRIPLE "aarch64-pc-windows-gnu" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "X86")
      set(AV_TARGET_TRIPLE "i686-pc-windows-gnu" CACHE INTERNAL "The LLVM-like target triple")
    else()
      message(FATAL_ERROR "Unknown Windows architecture: ${CMAKE_SYSTEM_PROCESSOR}!")
    endif()
  else()
    message(FATAL_ERROR "Unknown Windows compiler/toolchain: ${CMAKE_CXX_COMPILER_ID}!")
  endif()
elseif(APPLE)
  # We use CMAKE_OSX_ARCHITECTURES on Apple
  list(FIND CMAKE_OSX_ARCHITECTURES "x86_64" DARWIN_HAS_X86_64)
  list(FIND CMAKE_OSX_ARCHITECTURES "arm64" DARWIN_HAS_ARM64)
  if(NOT DARWIN_HAS_X86_64 EQUAL -1 AND DARWIN_HAS_ARM64 EQUAL -1)
    set(AV_TARGET_TRIPLE "x86_64-apple-darwin" CACHE INTERNAL "The LLVM-like target triple")
  elseif(DARWIN_HAS_X86_64 EQUAL -1 AND NOT DARWIN_HAS_ARM64 EQUAL -1)
    set(AV_TARGET_TRIPLE "aarch64-apple-darwin" CACHE INTERNAL "The LLVM-like target triple")
  elseif(NOT DARWIN_HAS_X86_64 EQUAL -1 AND NOT DARWIN_HAS_ARM64 EQUAL -1)
    set(AV_TARGET_TRIPLE "universal-apple-darwin" CACHE INTERNAL "The LLVM-like target triple")
  else()
    message(FATAL_ERROR "Unrecognized Darwin architecture in CMAKE_OSX_ARCHITECTURES: ${CMAKE_OSX_ARCHITECTURES}!")
  endif()
elseif(LINUX)
  if(AV_COMPILER_IS_GNU)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(ia64|x86_64|x64)")
      set(AV_TARGET_TRIPLE "x86_64-unknown-linux-gnu" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i386|i686)")
      set(AV_TARGET_TRIPLE "${CMAKE_SYSTEM_PROCESSOR}-unknown-linux-gnu" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(aarch64_be|aarch64|armv8b|armv8l|arm64|aarch64)")
      set(AV_TARGET_TRIPLE "aarch64-unknown-linux-gnu" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
      set(AV_TARGET_TRIPLE "arm-unknown-linux-gnu" CACHE INTERNAL "The LLVM-like target triple")
    else()
      message(FATAL_ERROR "Unhandled Linux architecture: ${CMAKE_SYSTEM_PROCESSOR}. Please file a bug report.")
    endif()
  elseif(AV_COMPILER_IS_LLVM)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(ia64|x86_64|x64)")
      set(AV_TARGET_TRIPLE "x86_64-unknown-linux-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i386|i686)")
      set(AV_TARGET_TRIPLE "${CMAKE_SYSTEM_PROCESSOR}-unknown-linux-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(aarch64_be|aarch64|armv8b|armv8l|arm64|aarch64)")
      set(AV_TARGET_TRIPLE "aarch64-unknown-linux-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
      set(AV_TARGET_TRIPLE "arm-unknown-linux-gnullvm" CACHE INTERNAL "The LLVM-like target triple")
    else()
      message(FATAL_ERROR "Unhandled Linux architecture: ${CMAKE_SYSTEM_PROCESSOR}. Please file a bug report.")
    endif()
  else()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "(ia64|x86_64|x64)")
      set(AV_TARGET_TRIPLE "x86_64-unknown-linux-unknown" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(i386|i686)")
      set(AV_TARGET_TRIPLE "${CMAKE_SYSTEM_PROCESSOR}-unknown-linux-unknown" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "(aarch64_be|aarch64|armv8b|armv8l|arm64|aarch64)")
      set(AV_TARGET_TRIPLE "aarch64-unknown-linux-unknown" CACHE INTERNAL "The LLVM-like target triple")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
      set(AV_TARGET_TRIPLE "arm-unknown-linux-unknown" CACHE INTERNAL "The LLVM-like target triple")
    else()
      message(FATAL_ERROR "Unhandled Linux architecture: ${CMAKE_SYSTEM_PROCESSOR}. Please file a bug report.")
    endif()
  endif()
else()
  message(FATAL_ERROR "Cannot handle different system than Windows/Linux/Darwin. Please file a bug report.")
endif()
